Updated the lint command to use golint

diff --git a/Server/Makefile b/Server/Makefile
--- a/Server/Makefile
+++ b/Server/Makefile
@@ -3,6 +3,7 @@
 GOPATH ?= $(shell go env GOPATH)
 GOOS ?= $(shell go env GOOS)
 GOARCH ?= $(shell go env GOARCH)
+GOLINT ?= $(shell go list -f {{.Target}} golang.org/x/lint/golint)
 GOFLAGS ?= $(GOFLAGS:) -mod=vendor
 LDFLAGS = -s -w
 GO = go
@@ -43,19 +44,32 @@ run: build
 	./$(DIST_ROOT)/server
 
 lint:
+	@echo • Checking gofmt
 	@for package in $$(go list ./...); do \
-		echo "Checking "$$package; \
+		echo "  - Checking "$$package; \
 		files=$$(go list -f '{{range .GoFiles}}{{$$.Dir}}/{{.}} {{end}}' $$package); \
 		if [ "$$files" ]; then \
 			gofmt_output=$$(gofmt -d -s $$files 2>&1); \
 			if [ "$$gofmt_output" ]; then \
+				echo "\033[1;33m" \
 				echo "$$gofmt_output"; \
-				echo "Gofmt failure"; \
+				echo "\033[31mGofmt failure ❌\033[0m";\
 				exit 1; \
 			fi; \
 		fi; \
 	done
-	@echo Gofmt success
+	@echo "\033[92mGofmt success ✅\033[0m"
+	@echo
+	@echo • Checking golint
+	@output=$$($(GOLINT) ./...); \
+	if [ "$$output" ]; then \
+		while IFS= read -r line; do \
+			echo "  - \033[1;33m$$line\033[0m"; \
+		done <<< "$$output" ; \
+		echo "\033[31mGolint failure ❌\033[0m"; \
+		exit 1; \
+	fi; \
+	@echo "\033[Golint success ✅\033[0m";
 
 fix-lint:
 	go fmt ./...
